version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://lox:password@db:5432/mydb?sslmode=disable
      - REDIS_URL=redis://redis:6379

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: lox
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
